### ISSUE TITLE
Problem deploying to OpenFaas

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/fn-prevalence-predictor#2]
@onlyjsmith we have a strange issue with the deployment of this function. As you might remember, it makes a call to another function on OpenFaas `fn-covariate-extractor` (in case that makes a difference). It runs fine locally, has deployed without any issues, but when I try and invoke a run on OpenFaas it just keeps running. I've tried checking the logs but can't see anything obvious. There is something in there about problem reading final line, but I think this is just a warning issued by R rather than an error. Could you take a look?

**Comment by onlyjsmith** [comment]
Er, there were quite a few reasons it wasn't working!

1. Ideally it needs to be modelled off an existing repo: I've made some changes (incl. #3 closed pull request), but we might need a better overall approach
2. Need to add more param checkers (see #7)
2. Would be great to add a simpler test that returns faster (see #4)
3. There's one large-ish change needed, which is around handling JSON. I've started the work on this (#8), but it has implications for the `gears` code (see https://github.com/disarm-platform/disarm-gears/issues/6)

**Comment by onlyjsmith** [comment]
So, superseding some of the above... I've had some success today with the _templates_ approach. 

I've rewritten this function using a template we can use from https://github.com/locational/faas-templates. Check that repos' README for a quick intro to using the templates. 

Template approach seems to be _much_ faster and easier to get started with, but with an extra step to debug the full function.

It's currently in PR #9 to take a look. We should not merge both #9 and #5 - they have different foundations.

**Comment by onlyjsmith** [comment]
Update: we think that the '502 Bad gateway' errors were coming due to timeouts. Ideally it would have given us a clearer error message, but it doesn't! We've extended the timeouts to around 1000 seconds.

Can you test it? Should find it deployed as [v0.2.0](https://github.com/disarm-platform/fn-prevalence-predictor/releases/tag/v0.2.0)

There's a more general question here, around how long should we allow functions to run for, in general. (Have added https://github.com/disarm-platform/algorithms-issues/issues/5)

**Comment by onlyjsmith** [comment]
This seems to have cleared up. Closing.
