### ISSUE TITLE
cannot run again on output of previous run

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor#20]
Running on the output of a previous run seems to cause an error
`
Error from function: : Error in (function (formula, family = gaussian(), data = list(), weights = NULL, :
Not enough (non-NA) data to do anything meaningful
`

Should we be able to rerun the function on the same data? If yes, it might be an issue with format/structure of return data.

**Comment by onlyjsmith** [comment]
Think this might be a problem with a client, not with the function: I've rerun by hand on command-line and it works ok.

Will update with more or close.

**Comment by onlyjsmith** [comment]
Can reproduce. 

1. Take the BNG features [e.g. from here](https://gist.github.com/onlyjsmith/d9acb6441d2283d5a8050b6758d5c4df).
2. Run against fn-prev-pred, with no other params.
3. Catch the output (should run fine).
4. Extract the `result` (FeatureCollection), and send as `point_data` for another run.
5. Fails, with error something like above.

So, same question as above - should we be able to send the output back for another run? Related, if not, what checks can we put in place to stop the crash, or make it make more sense to someone receiving it?

@HughSt can you take a look, have a think?

**Comment by ric70x7** [comment]
I found where the problem is.
1 First we pass a json with the features: n_positive, n_trials, geometry, id
2 The output is another json with the same features plus prevalence_bci_width, exceedance_uncertainty

If we don't pass the parameter exceedance thresholod in step 1, then the request in step 2 will have a feature of exceedance_uncertainty with None values.
At some point during the data preprocessing, we get rid of the None values, and in this case we eliminate all the datapoints.

Possible solutions:
a) drop any features form the json request that are not n_positive, n_trials or id
b) allow the user to specify which features in the request are covariates and should be incorporated into the model in addition to the ones we get through the covariate extractor.

**Comment by onlyjsmith** [comment]
Great - thanks for taking a look. Maybe we discuss on team call today if there’s time?
